### ISSUE TITLE
[Portal] Buttons in loading state can be interacted with

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#448]
A button in loading state can still be tapped, triggering multiple same request.

**Comment by axolotl0212** [comment]
should be fixed by https://github.com/authgear/authgear-server/blob/15ffb6551e96a0b5c9c2b0f170f32ab0fd5e9083/portal/src/ButtonWithLoading.tsx#L34

**Comment by kiootic** [comment]
I would suggest to avoid using `pointerEvents: none` for disabling user interaction in most cases, as it does not disable keyboard interaction.

**Comment by kiootic** [comment]
Also, it seems the loading button shifting upward problem you've mentioned in #436 still presents (e.g. when removing identity). Changing the spinner size to `xSmall` seems to fix the problem.

**Comment by axolotl0212** [comment]
> Also, it seems the loading button shifting upward problem you've mentioned in #436 still presents (e.g. when removing identity). Changing the spinner size to `xSmall` seems to fix the problem.

You are right, for `removing identity` the shift is very subtle (I didn't spot this one). Changing to smaller icon solves the problem
